### ISSUE TITLE
CustomerUser config should not get overwritten

### ISSUE THREAD

**Issue by thorsteneckel** [znuny/Znuny4OTRS-CTI#4]
Currently the File [Znuny4OTRSCTI.pm](https://github.com/znuny/Znuny4OTRS-CTI/blob/master/Kernel/Config/Files/Znuny4OTRSCTI.pm) overwrites the CustomerUser config. This can have different implications which can cause errors like wrong/not loaded CustomerUser configs, wrong CustomerUser BackendModules etc.

We should replace the file by a 1.1 config file that adds the UserPhone attribute (if given) to the CustomerUser [CustomerUserSearchFields](https://github.com/znuny/Znuny4OTRS-CTI/blob/master/Kernel/Config/Files/Znuny4OTRSCTI.pm#L41) configurations.

**Comment by thorsteneckel** [comment]
A workaround would be to use the CustomerUser config from the Defauls.pm and add it to the Config.pm if no custom CustomerUser config present yet. After that the 'phone' (or matching storage field) string have to be added to the 'CustomerUserSearchFields' list like in: https://github.com/znuny/Znuny4OTRS-CTI/blob/master/Kernel/Config/Files/Znuny4OTRSCTI.pm#L41

**Comment by rkaldung** [comment]
I'd like to talk about this :-)

**Comment by rkaldung** [comment]
Yes
