### ISSUE TITLE
Can't auto fill email address in IE11

### ISSUE THREAD

**Issue by NeverMin** [znuny/Znuny4OTRS-CTI#6]
/otrs/index.pl?Action=AgentTicketPhoneCTI;CallerID=18101792535

**Comment by thorsteneckel** [comment]
HI @NeverMin - thanks for your feedback. We'll take a loot at this.

**Comment by NeverMin** [comment]
@thorsteneckel @jepf Can you let me try to fix? first.

**Comment by thorsteneckel** [comment]
Sure! Let us know if we should take over.

**Comment by NeverMin** [comment]
Hi @thorsteneckel , I'm done.

**Comment by NeverMin** [comment]
fixed in v5.0.1.
