### ISSUE TITLE
Feature Request: Regular Expression for Number-Substitution

### ISSUE THREAD

**Issue by jenseickmeier** [znuny/Znuny4OTRS-CTI#8]
Hi,
we have a feature request for AgentTicketPhoneCTI.pm.
Is it possible to set an regExp for the CallerID in SysConfig so that only the phone extension will be transported to OTRS.
We have modified the code in our system like this:

my $SearchCallerID = $CallerID;
$SearchCallerID =~ s/^\+{0,1}49208455/*455 /;
$SearchCallerID =~ s/^\+{0,1}49208/*/;

#find customer
my %CustomerUserList = $CustomerUserObject->CustomerSearch(
#Search => $CallerID,
Search => $SearchCallerID,

It would be very nice, if we can configure the $SearchCallerID via SysConfig.

Best regards,
Jens

**Comment by dennykorsukewitz** [comment]
Hi @jenseickmeier,

thank you for your great idea. We have implemented it in the newest version. 5.0.2
A feedback would be great.

best regards
Denny
