### ISSUE TITLE
Passing HTTP_LINK to UserPhone 

### ISSUE THREAD

**Issue by sameer615** [znuny/Znuny4OTRS-CTI#9]
Hey ,
I'm trying make any customer information field clickable or pass http-link to any field .
so i have tried this 
**[ 'UserPhone',   'Phone',   'phone',    1, 0, 'var', 'click2dial.pl?cust=$Env{"UserPhone"}', 0],**
OR 
**[ 'UserPhone',   'Phone',   'phone',    1, 0, 'var', 'click2dial.pl?cust=$Data{"UserPhone"}', 0],**
OR 
**[ 'UserPhone',   'Phone',   'phone',    1, 0, 'var', 'click2dial.pl?cust=$Env{"UserPhone"}', 0],**

its giving  **http://192.168.2.122/otrs/click2dial.pl?cust=$Env{**

So I've tried without double quotes like this 
[ 'UserPhone',   'Phone',   'phone',    1, 0, 'var', 'click2dial.pl?cust=$Env{**UserPhone**}', 0],

its simply giving 
http://192.168.2.122/otrs/click2dial.pl?cust=$Env{UserPhone}

So can you help in order to get values like this 
http://192.168.2.122/otrs/click2dial.pl?cust=9864975877

**Comment by rkaldung** [comment]
Hi @sameer615,

The placeholder follow the default OTRS syntax: 
``[% Data.VARIABLE %]``

For your example try the following:
``
[ 'UserPhone', 'Phone', 'phone', 1, 0, 'var', 'click2dial.pl?cust=[% Data.UserPhone %]', 0],
``

**Comment by sameer615** [comment]
Hi Roy Kaldung,

Thanks  a lot , i have been trying since last Monday.

Thanks again.

Regards
Sameer Sardar

**Comment by sameer615** [comment]
Hi @rkaldung 

Can you help to pass logged in user id in http-link 
For Example : 
Pass logged in agent id in link 
[ 'UserPhone', 'Phone', 'phone', 1, 0, 'var', 'click2dial.pl?CustID=[% Data.AgentID%]', 0], 

Something like above and get URL like :

http://192.168.2.122/otrs/click2dial.pl?CustID=12

**Comment by rkaldung** [comment]
Hi @sameer615 ,

This is not related to this add-on please use the community forum http://forums.otterhub.org/index.php for questions like this 

hth, Roy
